name: Auto Fetch 2D Data

on:
  schedule:
    # နေ့စဉ် မြန်မာစံတော်ချိန် နေ့လည် (၁၂:၃၀) နှင့် ညနေ (၄:၃၀) ခန့်တွင် Auto အလုပ်လုပ်မည်
    - cron: '0 6,10 * * 1-5'
  workflow_dispatch: # မိမိဘာသာ Manual စမ်းသပ်ရန် ခလုတ်

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Fetch Script
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: python fetch_data.py
